name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
        uses: lowlighter/metrics@latest
        with:
          config_output: insights
          token: ${{ secrets.TOKEN_METRICS }}
          
